export const STORE_EMAIL = 'STORE_EMAIL';

export const GET_CURRENCIES = 'GET_CURRENCIES';

export const STORE_EXPENSE = 'STORE_EXPENSE';

export const REMOVE_EXPENSE = 'REMOVE_EXPENSE';

export const EDIT_EXPENSE = 'EDIT_EXPENSE';

export const EDITING_EXPENSE = 'EDITING_EXPENSE';
